version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    environment: 
      - AWS_DEFAULT_REGION=us-west-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"