service: mbo-backend

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: 
      forceExclude:
        - aws-sdk

  profiles:
    local: mbo
    # dev: profile-dev
    # staging: profile-staging
    # prod: profile-prod
  environment:
    default_env: &default_env
      SERVERLESS_SERVICE: ${self:service}
      SERVERLESS_STAGE: ${self:provider.stage}
      SERVERLESS_VERSION: ${file(./package.json):version}
      SERVERLESS_REGION: ${opt:region, self:provider.region}
    local:
      <<: *default_env
      stage: local
    dev:
      <<: *default_env
      stage: dev
    stating:
      <<: *default_env
      stage: staging
    prod:
      <<: *default_env
      stage: prod

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'} # Set the default stage used. Default is dev
  region: ${opt:region, 'us-east-1'} # Overwrite the default region used. Default is us-east-1
  profile: ${self:custom.profiles.${self:provider.stage}, 'mbo'}
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  logRetentionInDays: 30 # Set the default RetentionInDays for a CloudWatch LogGroup
  environment: ${self:custom.environment.${self:provider.stage}}

package: # Optional deployment packaging configuration
  include: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  apiRequest:
    handler: handler.request
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-webpack
  - serverless-offline

resources:
  Resources:
    HealthCheckLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 1
